services:
  ai-gpu-environment:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-gpu-container
    runtime: nvidia # Enable GPU support via NVIDIA runtime
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    volumes:
      - ./code:/code # Shared volume between host and container
    working_dir: /code # Set working directory inside the container
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''
    ports:
      - "8888:8888"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility # Enable compute/utility capabilities
      - PYTHONUNBUFFERED=1 # Ensures immediate output to logs
